# -*- mode: ruby -*-
# vi: set ft=ruby:
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"  # Box for the *control* machine

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"  # Memory for all VMs (unless overridden)
    vb.cpus = "1"    # CPUs for all VMs (unless overridden)
  end

  # Node 1 virtual machine 1
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.56.101"
    node1.vm.network "forwarded_port", guest: 80, host: 8100, auto_correct: true
  end

  # Node 2 virtual machine 2
  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "192.168.56.102"
    node2.vm.network "forwarded_port", guest: 5000, host: 5000, auto_correct: true
  end

  # Controlador Machine
  config.vm.define "controlador" do |controlador|
    controlador.vm.hostname = "controlador"
    controlador.vm.network "private_network", ip: "192.168.56.100"
  end

  # Provisionador Ansible machines
  config.vm.provision "ansible_local", run: "always" do |ansible|
    ansible.inventory_path = "ansible/hosts"
    ansible.playbook = "ansible/playbook.yml"
    ansible.become = true
    ansible.verbose = false
    ansible.install = true
  end
end