Vagrant.configure("2") do |config|
    
    config.vm.provider "virtualbox" do |vb|
        # Customize the amount of memory on the VM:
        vb.memory = "1024"
    end

    # master virtual machine
    config.vm.define "master" do |master|    
      master.vm.box = "ubuntu/jammy64"
      master.vm.hostname = "master.local"
      master.vm.network "private_network", ip: "192.168.56.2"
    end
  
    # slave 1 virtual machine
    config.vm.define "slave1" do |slave1|
      slave1.vm.box = "ubuntu/jammy64"
      slave1.vm.network :private_network, ip: "192.168.56.3"
      slave1.vm.hostname = "slave1.local"
    end
  
    # slave 1 virtual machine
    config.vm.define "slave2" do |slave2|
      slave2.vm.box = "ubuntu/jammy64"
      slave2.vm.network :private_network, ip: "192.168.56.4"
      slave2.vm.hostname = "slave2.local"
    end
  end